spring.application.name=menu-digital
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d75sjlffte5s73e8enp0-a:5432/cardapiodb_m6cv
spring.datasource.username=admin
spring.datasource.password=IqDUAuyNV1JXQYUe5MURFFmBixvR8Ql9


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true